### PR TITLE
Fix error: wget: not an http or ftp url

### PR DESCRIPTION
**Pull request by markshust**
This fixes one issue with https://github.com/brikis98/docker-osx-dev/issues/61 -- one still remaining

### CODE REVIEW

**Comment by brikis98** [comment]
The reason we're downloading rsync from this repo is as a work around for #52, where Docker's latest Boot2Docker ISO was upgraded to a 64 bit image that no longer had rsync in the package repository. @cameronbrunner did the work to get rsync into the package repository earlier today, so it's probably on all the mirrors now and we can go back to the simpler `tce-load -wi rsync` solution. 

Could you run:

```
boot2docker ssh
tce-load -wi rsync
```

And let me know what you see? If it works, then a better PR would be to just revert [this commit](https://github.com/brikis98/docker-osx-dev/commit/4f7c4f764848cba431336f9cad586d1e93da19f4). Thanks!

**Comment by markshust** [comment]
I tried that, unfortunately it didn't work... a `which rsync` returned a blank line.

**Comment by brikis98** [comment]
Did the install actually complete or did it give you an error?

**Comment by markshust** [comment]
Actually nothing happened with that line... it's just like a hit a carriage return :?

**Comment by brikis98** [comment]
That's... very odd. I'll try to repro myself tomorrow.

**Comment by brikis98** [comment]
OK, just tried to repro, and it looks like the version installed by `tce-load` may have issues. When you run it, you get this error:

```
rsync: error while loading shared libraries: libattr.so.1: cannot open shared object file: No such file or directory
```

So I guess that means this workaround has to stay. Therefore, I've merged your PR. Thanks for the fix!

**Comment by cameronbrunner** [comment]
I have the .dep submitted that will automatically include attr and acl when doing a `tce-load -wi rsync`.  Until the dep is active and sync'ed this should work `tce-load -wi rsync acl attr` as a work-around.

**Comment by cameronbrunner** [comment]
FYI @brikis98 the TCL team took the .dep file so automatic dependency download should be done with `tce-load -wi rsync` now.

**Comment by brikis98** [comment]
@cameronbrunner Thanks. It looks like the install works and the rsync executable runs, but the installer exits with an error code:

```
docker@boot2docker:~$ tce-load -wi rsync
rsync.tcz.dep OK
acl.tcz.dep OK
Downloading: attr.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
attr.tcz             100% |************************************************************************************************************************************| 24576   0:00:00 ETA
attr.tcz: OK
Downloading: acl.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
acl.tcz              100% |************************************************************************************************************************************| 40960   0:00:00 ETA
acl.tcz: OK
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz            100% |************************************************************************************************************************************|   312k  0:00:00 ETA
rsync.tcz: OK
docker@boot2docker:~$ echo $?
1
```

Any idea why?

**Pull request merged**
