### PR TITLE
Fix/integration test 114

### PR DESCRIPTION
**Pull request by ain**

### CODE REVIEW

**Comment by brikis98** [comment]
Looks good, thanks!

**Comment by brikis98** [comment]
Oops, just noticed your comment in #114. What file rights issues are you having?

**Comment by ain** [comment]
It's basically this:

```
[TEST_INFO] Testing mounting a folder with Alpine Linux image
cat: can't open '/src/test-project/test-file': No such file or directory
test/integration-test.sh: line 44: [[: test file contents: syntax error in expression (error token is "file contents")
```

as in respect to `/src/test-project` being:

```
drwxr-xr-x    1 1000     50             102 Sep 28 23:38 .
drwxr-xr-x   23 root     root          4096 Sep 29 19:09 ..
-rw-r--r--    1 1000     50              19 Sep 29 19:09 test-file
```

So to me it sounds like file rights problem when mounting the host folder.

**Comment by brikis98** [comment]
Are you sure it's a permissions issue? It could just be that file syncing isn't working correctly during the test or docker-osx-dev isn't running or similar. What happens if you change the `cat` command in the `test_docker_mount` function to a simple `ls` in the same folder?

**Comment by ain** [comment]
Yes, it is confusing:

```
[TEST_INFO] Testing mounting a folder with Alpine Linux image
ls: /src/test-project/test-file: No such file or directory
```

and

```
$ docker run --rm -v $(pwd):/src gliderlabs/alpine:3.2 /bin/sh -c "ls -la /src/test-project/test-file"
-rw-r--r--    1 1000     50              19 Sep 29 22:25 /src/test-project/test-file
```

**Comment by brikis98** [comment]
The issue is probably that the test code isn't running in the right folder. For example, I just noticed that the `create_test_project` function does `cd "$TEST_FOLDER"`, which probably messes up the mounting of the current directory (`-v $(pwd):/src`).

**Pull request merged**
