### PR TITLE
Moving the boot2docker init from setup to docker-osx-dev (all test pa…

### PR DESCRIPTION
**Pull request by Simperfit**
…ssed)

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for putting this together! Since integration tests are still blocked (see #7), I have to ask: did you run the local versions of `setup.sh` and `docker-osx-dev` to make sure things are still working?

**Comment by Simperfit** [comment]
brikis98, Yes i've tested both, and i'm using the modified docker-osx-dev already.

**Comment by brikis98** [comment]
Fantastic. Thank you!

**Comment by Simperfit** [comment]
I've tried on my machine and in a new machine today.

We need the init_boot2docker in both it doest not write the /etc/hosts if the init is not in the setup, it does not install it

I will send a new PR with this.

**Comment by brikis98** [comment]
Ah, you're right. The `/etc/hosts` entry depends on the `boot2docker ip` command. I guess for now, you can have the same functions in both scripts. I filed #39 to track the need to extract that duplicated functionality into a single, shared location.

**Pull request merged**
