### PR TITLE
Config proper path to SSH private key file

### PR DESCRIPTION
**Pull request by yoanisgil**

### CODE REVIEW

**Comment by yoanisgil** [comment]
I'm running docker-machine 0.5:

  docker-machine --version
  docker-machine version 0.5.0 (04cfa58)

and I was getting this warning:

```
2015-12-07 20:36:48 [INFO] Warning: Identity file /Users/brujitos/.docker/machine/id_rsa not accessible: No such file or directory.
```

So I put this really tiny PR together ;). Let me know what you think.

**Comment by brikis98** [comment]
Thanks for the PR!

Any idea if the location of the file changed in some recent version of Docker Machine?

Also, why are tests failing?

**Comment by yoanisgil** [comment]
You're welcome. I just probably squash the commits ;) but l think we should first:
- Get CI to pass
- Test with machine's previous version (since I'm using docker 1.9 which is only a couple of months old ;))

As for tests this is the issue:

```
ok 79 init_docker_host should call configure_boot2docker set DOCKER_HOST vars
not ok 80 configure_docker_machine should set DOCKER_HOST vars
# (from function `assert_equal' in file test/test_helper.bash, line 29,
#  in test file test/docker-osx-dev.bats, line 453)
#   `assert_equal "DOCKER_INSPECT_OUTPUT/id_rsa" "$DOCKER_HOST_SSH_KEY"' failed
# expected: DOCKER_INSPECT_OUTPUT/id_rsa
# actual:   DOCKER_INSPECT_OUTPUT/machines/some-machine/id_rsa
```

Maybe I should update  the test suite?

**Comment by yoanisgil** [comment]
And, no I cannot really say whether the file location changed. Which is why I think we need to test at least with machine's previous version.

**Comment by brikis98** [comment]
Ah, OK. Yes, please update the test and check if this works on an older version of Docker Machine. If not, we may need to check both the old and new paths for `id_rsa` for backwards compatibility.

**Comment by yoanisgil** [comment]
Will do. Thanks.

**Comment by mariomarin** [comment]
Isn't this pull request a duplicate of #145?

**Comment by brikis98** [comment]
Ha, you're right! Unfortunately, GitHub doesn't seem to send a notification when a PR is updated, so I completely forgot about that one.

**Comment by yoanisgil** [comment]
@brikis98 @mariomarin indeed it is ;). Would be nice if it could be merged ;)

**Comment by brikis98** [comment]
Just merged it. Thanks folks!

**Pull request closed without merging**
