### PR TITLE
patch getbuild to fix tce-load rsync on boot2docker 1.7

### PR DESCRIPTION
**Pull request by leemhenson**
Pretty ugly fix for #52 but it's a starting point for a discussion. :dancer:

### CODE REVIEW

**Comment by codedmart** [comment]
@leemhenson This does not work for me:

```
2015-06-23 09:46:44 [INFO] Installing rsync in the Boot2Docker image
Boot2Docker version 1.7.0, build master : 7960f90 - Thu Jun 18 18:31:45 UTC 2015
Docker version 1.7.0, build 0baf609
rsync.tcz.dep OK
Downloading: popt.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
popt.tcz             100% |*******************************| 28672   0:00:00 ETA
popt.tcz: OK
Downloading: rsync.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
rsync.tcz            100% |*******************************|   180k  0:00:00 ETA
rsync.tcz: OK
error in run: exit status 1
```

**Comment by leemhenson** [comment]
Yeah I just saw that. For some reason `tce-load` returns 1 despite succeeding? I guess we could swallow the exit code?

**Comment by leemhenson** [comment]
yeah rsync seems to be silently hanging for me too. abort mission!

**Comment by codedmart** [comment]
@leemhenson I haven't tried this yet, but https://github.com/boot2docker/boot2docker/issues/936#issuecomment-114675231.

**Pull request closed without merging**
